import { NextResponse } from "next/server";
import { getSession, getSessionReadOnly, validateCsrf, writeAuditLog } from "@/lib/auth";
import fs from "fs";
import path from "path";
import { validateUpload, UPLOAD_PRESETS } from "@career-builder/security/file-upload";
import { isPathSafe } from "@career-builder/security/file-upload";
import { createStorage } from "@career-builder/shared/storage";
import { getRateLimiter, getClientIp } from "@career-builder/security/rate-limit";

const MEDIA_DIR = path.join(process.cwd(), "data", "media");
const PUBLIC_PATH = "/api/media/file"; // served via GET (local driver only)

// Durable object storage in production (STORAGE_DRIVER=blob|s3); the local
// filesystem driver (dev default) is ephemeral on serverless. The GET listing
// below reflects the local driver only — in cloud mode, media URLs persist in
// page blocks and via the returned URL, but the library listing is local.
function mediaStorage() {
  return createStorage({
    localDir: MEDIA_DIR,
    localPublicPrefix: PUBLIC_PATH,
    keyPrefix: "media",
  });
}

function ensureDir() {
  if (!fs.existsSync(MEDIA_DIR)) {
    fs.mkdirSync(MEDIA_DIR, { recursive: true });
  }
}

/** POST /api/media — upload a file (auth required, editor+) */
export async function POST(req: Request) {
  const session = await getSession();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  if (session.role === "viewer") {
    return NextResponse.json({ error: "Insufficient permissions" }, { status: 403 });
  }

  const csrfValid = await validateCsrf(req);
  if (!csrfValid) {
    return NextResponse.json({ error: "Invalid CSRF token" }, { status: 403 });
  }

  // Rate limit uploads per user
  const limiter = getRateLimiter("api");
  const ip = getClientIp(req) || "unknown";
  if (!limiter.check(`media-upload:${session.userId}:${ip}`).allowed) {
    return NextResponse.json({ error: "Upload rate limit exceeded. Please try again later." }, { status: 429 });
  }

  const formData = await req.formData();
  const file = formData.get("file") as File | null;

  if (!file) {
    return NextResponse.json({ error: "No file provided" }, { status: 400 });
  }

  // Read file buffer for magic byte validation
  const buffer = Buffer.from(await file.arrayBuffer());

  // Validate using security package — checks extension, MIME, magic bytes, size, SVG scripts
  const validation = validateUpload(
    { name: file.name, size: file.size, type: file.type },
    buffer,
    UPLOAD_PRESETS.media,
  );

  if (!validation.valid) {
    return NextResponse.json({ error: validation.error }, { status: 400 });
  }

  // Use the cryptographically safe filename generated by security package
  const uniqueName = validation.safeFilename!;

  // Verify path is safe (no directory traversal)
  if (!isPathSafe(uniqueName, MEDIA_DIR)) {
    return NextResponse.json({ error: "Invalid file path" }, { status: 400 });
  }

  // Durable in production; local filesystem in dev.
  const stored = await mediaStorage().put(uniqueName, buffer, file.type || "application/octet-stream");

  writeAuditLog(session.userId, session.email, "media_upload", `file: ${uniqueName} (${validation.detectedType})`);

  return NextResponse.json({
    url: stored.url,
    name: uniqueName,
    size: file.size,
    type: file.type,
  });
}

/** GET /api/media — list uploaded media */
export async function GET() {
  const session = await getSessionReadOnly();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  ensureDir();

  const files = fs.readdirSync(MEDIA_DIR).filter((f) => !f.startsWith("."));

  const media = files.map((name) => {
    const stat = fs.statSync(path.join(MEDIA_DIR, name));
    return {
      name,
      url: `${PUBLIC_PATH}/${name}`,
      size: stat.size,
      modified: stat.mtime.toISOString(),
    };
  });

  // Newest first
  media.sort((a, b) => b.modified.localeCompare(a.modified));

  return NextResponse.json({ media });
}
