import { NextResponse } from "next/server";
import { getSession, getSessionReadOnly, validateCsrf, writeAuditLog } from "@/lib/auth";
import fs from "fs";
import path from "path";
import { validateUpload, UPLOAD_PRESETS } from "@career-builder/security/file-upload";
import { isPathSafe } from "@career-builder/security/file-upload";

const MEDIA_DIR = path.join(process.cwd(), "data", "media");
const PUBLIC_PATH = "/api/media/file"; // served via GET

// ⚠️ On Vercel, filesystem is ephemeral — uploaded files will be lost between deployments.
// TODO: Migrate to cloud storage (S3, Cloudflare R2, or Vercel Blob) for production.
const IS_VERCEL = !!process.env.VERCEL;

function ensureDir() {
  if (!fs.existsSync(MEDIA_DIR)) {
    fs.mkdirSync(MEDIA_DIR, { recursive: true });
  }
}

/** POST /api/media — upload a file (auth required, editor+) */
export async function POST(req: Request) {
  const session = await getSession();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  if (session.role === "viewer") {
    return NextResponse.json({ error: "Insufficient permissions" }, { status: 403 });
  }

  const csrfValid = await validateCsrf(req);
  if (!csrfValid) {
    return NextResponse.json({ error: "Invalid CSRF token" }, { status: 403 });
  }

  const formData = await req.formData();
  const file = formData.get("file") as File | null;

  if (!file) {
    return NextResponse.json({ error: "No file provided" }, { status: 400 });
  }

  // Read file buffer for magic byte validation
  const buffer = Buffer.from(await file.arrayBuffer());

  // Validate using security package — checks extension, MIME, magic bytes, size, SVG scripts
  const validation = validateUpload(
    { name: file.name, size: file.size, type: file.type },
    buffer,
    UPLOAD_PRESETS.media,
  );

  if (!validation.valid) {
    return NextResponse.json({ error: validation.error }, { status: 400 });
  }

  ensureDir();

  // Use the cryptographically safe filename generated by security package
  const uniqueName = validation.safeFilename!;
  const filePath = path.join(MEDIA_DIR, uniqueName);

  // Verify path is safe (no directory traversal)
  if (!isPathSafe(uniqueName, MEDIA_DIR)) {
    return NextResponse.json({ error: "Invalid file path" }, { status: 400 });
  }

  fs.writeFileSync(filePath, buffer);

  if (IS_VERCEL) {
    console.warn("[media] File written to ephemeral filesystem on Vercel — will be lost on next deployment. Consider migrating to cloud storage.");
  }

  const url = `${PUBLIC_PATH}/${uniqueName}`;

  writeAuditLog(session.userId, session.email, "media_upload", `file: ${uniqueName} (${validation.detectedType})`);

  return NextResponse.json({
    url,
    name: uniqueName,
    size: file.size,
    type: file.type,
  });
}

/** GET /api/media — list uploaded media */
export async function GET() {
  const session = await getSessionReadOnly();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  ensureDir();

  const files = fs.readdirSync(MEDIA_DIR).filter((f) => !f.startsWith("."));

  const media = files.map((name) => {
    const stat = fs.statSync(path.join(MEDIA_DIR, name));
    return {
      name,
      url: `${PUBLIC_PATH}/${name}`,
      size: stat.size,
      modified: stat.mtime.toISOString(),
    };
  });

  // Newest first
  media.sort((a, b) => b.modified.localeCompare(a.modified));

  return NextResponse.json({ media });
}
